tn {
  dw {
    type: Deposit
    acnt_id: 1
    asset_id: 1
    amount: "\x0d\xe0\xb6\xb3\xa7\x64\x00\x00"
  }
}
tn {
  cu {
    type: Commit
    acnt_id: 1
    st_id: 1
    amount: "\x0d\xe0\xb6\xb3\xa7\x64\x00\x00"
    timestamp: 100
  }
}
tn {
  cu {
    type: Commit
    acnt_id: 1
    st_id: 1
    amount: "\x0d\xe0\xb6\xb3\xa7\x64\x00\x00"
    timestamp: 200
  }
  # not enough idle balance
  flag: 2
}